services:

  nginx:
    image: nginx:1.17-alpine
    container_name: example-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/var/www/html
      # Mount config for development
      - ./docker/nginx:/etc/nginx/conf.d:cached

  php-fpm:
    build: docker/php-fpm
    restart: unless-stopped
    container_name: example-php
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html/

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 33061:3306
    volumes:
      - ./docker/dump:/docker-entrypoint-initdb.d
      - ./docker/storage/mysql:/var/lib/mysql
    environment:
        MYSQL_DATABASE: 'todo'
        MYSQL_ROOT_USER: 'root'
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        MYSQL_PASSWORD: 'root'
        MYSQL_ROOT_PASSWORD:

  redis:
    image: redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - ./:/var/www/html

  node:
    image: node:22-alpine3.19
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/
    ports:
        - 8081:5174
    tty: true
    working_dir: /var/www/html/
